<?php
/**
 * Plugin adapter for Yay Wholesale B2B Pro.
 * Generated by yaycommerce-init. Edit values as needed.
 */

defined( 'ABSPATH' ) || exit;

class YayWholesaleB2bProPluginAdapter implements \YayWholesaleB2BScoped\YayCommerce\AdminShell\License\Contracts\LicenseConfigAdapter {
    // --- Menu methods ---
    public function get_menu_title(): string         { return 'YayWholesale'; }
    public function get_page_title(): string         { return 'Yay Wholesale B2B Pro'; }
    public function get_menu_slug(): string          { return 'yay-wholesale-b2b-settings'; }
    public function get_settings_page_callback(): ?callable { return null; } // Set your render callback here
    public function get_settings_page_position(): ?int { return null; }
    public function get_capability(): string         { return 'manage_options'; }
    public function get_plugin_basename(): string    { return YAYWHOLESALEB2B_BASE_NAME; }
    public function get_settings_label(): string     { return 'Settings'; }
    public function get_docs_url(): string           { return 'https://docs.yaycommerce.com/yaywholesale/'; }
    public function get_pro_url(): string            { return ''; }

    // --- License methods ---
    public function get_plugin_slug(): string        { return 'yay-wholesale-b2b-pro'; }
    public function get_plugin_name(): string        { return 'Yay Wholesale B2B Pro'; }
    public function get_plugin_version(): string     { return defined( 'YAYWHOLESALEB2B_VERSION' ) ? YAYWHOLESALEB2B_VERSION : '0.0.0'; }
    public function get_plugin_file(): string        { return YAYWHOLESALEB2B_PLUGIN_DIR . 'yay-wholesale-b2b.php'; }
    public function get_item_id(): int               { return 66637; }
    public function get_store_url(): string          { return 'https://yaycommerce.com/'; }
    public function get_store_link(): string         { return 'https://yaycommerce.com/yay-wholesale-b2b-for-woocommerce/'; }

    /**
     * Check if this plugin has an active, non-expired license.
     */
    public static function is_licensed(): bool {
        $info = get_option( 'yay-wholesale-b2b-pro_license_info', [] );
        $key  = get_option( 'yay-wholesale-b2b-pro_license_key', '' );
        return ! empty( $key ) && ! empty( $info ) && 'expired' !== ( $info['license'] ?? '' );
    }
}
