<?php
namespace YayWholesaleB2B\Helpers;

use YayWholesaleB2B\Helpers\SettingsHelper;
use YayWholesaleB2B\Utils\Utils;
use WP_User_Query;

/**
 * Roles Helper Class
 */
class RolesHelper {

    public static function get_wholesale_roles(): array {
        return get_option( 'yaywholesaleb2b_roles', [] );
    }

    public static function get_active_wholesale_roles() {
        $roles = self::get_wholesale_roles();
        return array_values( array_filter( $roles, fn( $role ) => $role['status'] === true ) );
    }

    public static function save_wholesale_roles( array $roles ) {
        return update_option( 'yaywholesaleb2b_roles', $roles );
    }

    /**
     * Get default wholesale role config.
     *
     * @return array|null
     */
    public static function get_default_wholesale_role() {
        $wholesale_roles   = self::get_active_wholesale_roles();
        $setting           = SettingsHelper::get_settings();
        $default_role_slug = $setting['general']['default_role'];

        if ( ! empty( $default_role_slug ) ) {
            $default_role = self::get_role_by_slug( $wholesale_roles, $default_role_slug );
            if ( $default_role !== null ) {
                return $default_role;
            }
        }

        if ( ! empty( $wholesale_roles ) ) {
            return $wholesale_roles[0];
        }

        return null;
    }

    public static function generate_default_role() {
        $default_slug      = 'ywhs_default_role';
        $default_role_name = __( 'YayWholesale Role', 'yay-wholesale-b2b' );
        $default_role      = [
            'id'               => 1,
            'name'             => $default_role_name,
            'description'      => __( 'This is a default role generated by YayWholesale.', 'yay-wholesale-b2b' ),
            'discount'         => 0,
            'minOrderQuantity' => 0,
            'minOrderAmount'   => 0,
            'applyToSalePrice' => false,
            'status'           => true,
            'slug'             => $default_slug,
        ];

        add_role( $default_slug, $default_role_name, [ 'read' => true ] );
        self::save_wholesale_roles( [ $default_role ] );
        return $default_slug;
    }

    /**
     * Check if the user is a wholesale user.
     *
     * @param int $user_id The user ID.
     * @return array|null The user role or null if not found.
     */
    public static function is_wholesale_user( int $user_id = 0 ) {
        if ( ! is_user_logged_in() ) {
            return null;
        }

        $roles          = get_option( 'yaywholesaleb2b_roles', [] );
        $user           = $user_id > 0 ? get_user_by( 'ID', $user_id ) : wp_get_current_user();
        $user_role_slug = self::get_user_wholesale_role( $user, $roles );
        if ( ! $user_role_slug ) {
            return null;
        }

        $role = self::get_role_by_slug( $roles, $user_role_slug );
        if ( ! $role || ! isset( $role['status'] ) || ! $role['status'] ) {
            return null;
        }

        // Handle price (Compatible to other price-related plugins)
        $role['minOrderAmount'] = apply_filters( 'ywhs_price_handle_processed', $role['minOrderAmount'] );

        if ( ! Utils::is_pro() ) {
            $role['minOrderQuantity'] = 0;
        }

        return $role;
    }

    /**
     * Generate a unique role slug.
     *
     * @param string  $name The role name.
     * @param array[] $roles The roles array.
     * @return string The unique role slug.
     */
    public static function generate_unique_role_slug( string $name, array $roles ): string {
        $base  = sanitize_title( $name );
        $slugs = array_column( $roles, 'slug' );
        $slug  = $base;
        $i     = 1;
        while ( in_array( $slug, $slugs, true ) ) {
            $slug = "{$base}-{$i}";
            ++$i;
        }
        return $slug;
    }


    /**
     * Remove a WordPress role by slug.
     *
     * @param string $slug The role slug.
     * @return void
     */
    public static function remove_wp_role_by_slug( string $slug ): void {
        $wp_roles = wp_roles();
        if ( $wp_roles->is_role( $slug ) ) {
            $wp_roles->remove_role( $slug );
        }
    }

    /**
     * Get role config by slug.
     *
     * @param array[] $roles The roles array.
     * @param string  $slug The role slug.
     * @return array|null The role config or null if not found.
     */
    public static function get_role_by_slug( array $roles, string $slug ): ?array {
        return array_values( array_filter( $roles, fn( $role ) => isset( $role['slug'] ) && $role['slug'] === $slug ) )[0] ?? null;
    }

    /**
     * Get the wholesale role slug for the current user.
     *
     * @param \WP_User $user The user object.
     * @param array[]  $roles The roles array.
     * @return string|null The wholesale role slug or null if not found.
     */
    public static function get_user_wholesale_role( \WP_User $user, array $roles ): ?string {
        $meta_slug = get_user_meta( $user->ID, '_yaywholesaleb2b_role', true );
        if ( $meta_slug ) {
            return sanitize_title( $meta_slug );
        }

        // Fallback to WP role if slug matches
        foreach ( $user->roles as $wp_role ) {
            $role = self::get_role_by_slug( $roles, $wp_role );
            if ( $role ) {
                return $role['slug'];
            }
        }

        return null;
    }

    /**
     * Delete all the yay-wholesale-b2b's roles from the user.
     *
     * @param \WP_User $user The user object.
     * @return void
     */
    public static function remove_ywhs_role_from_user( \WP_User $user ): void {
        $role_slugs = array_column( get_option( 'yaywholesaleb2b_roles', [] ), 'slug' );

        foreach ( $role_slugs as $ywhs_role ) {
            if ( in_array( $ywhs_role, $user->roles, true ) ) {
                $user->remove_role( $ywhs_role );
            }
        }
    }

    /**
     * Handle the data of roles list option with setting
     *
     * @param array $roles The roles option.
     * @param array $settings The settings.
     * @return array
     */
    public static function handle_roles_data( array $roles, array $settings ) {
        foreach ( $roles as $key => &$role ) {
            $slug          = $role['slug'] ?? sanitize_title( $role['name'] );
            $user_query    = new WP_User_Query(
                [
                    'role'   => $slug,
                    'fields' => 'ID',
                    'number' => -1,
                ]
            );
            $count         = $user_query->get_total();
            $role['count'] = $count;
            if ( $count > 0 ) {
                $role['role_url'] = admin_url( 'users.php?role=' . rawurlencode( $slug ) );
            }
            $role['isDefault'] = $slug === $settings['general']['default_role'];

            if ( $role['isDefault'] ) {
                $default_index = $key;
            }

            if ( ! Utils::is_pro() ) {
                $role['minOrderQuantity'] = 0;
            }
        }//end foreach

        if ( isset( $default_index ) && $default_index < count( $roles ) - 1 ) {
            $default_role = $roles[ $default_index ];
            unset( $roles[ $default_index ] );
            $roles   = array_values( $roles );
            $roles[] = $default_role;
        }

        return $roles;
    }
}
