<?php
namespace YayWholesaleB2B\Helpers;

use YayWholesaleB2B\Helpers\SettingsHelper;
use YayWholesaleB2B\Utils\Utils;
use WP_User_Query;

/**
 * Roles Helper Class
 */
class RolesHelper {

    /**
     * Get wholesale role configs.
     *
     * @return array
     */
    public static function get_wholesale_roles(): array {
        return get_option( 'yaywholesaleb2b_roles', [] );
    }

    /**
     * Get active wholesale role configs.
     *
     * @return array
     */
    public static function get_active_wholesale_roles() {
        $roles = self::get_wholesale_roles();
        return array_values( array_filter( $roles, fn( $role ) => $role['status'] === true ) );
    }

    /**
     * Save wholesale role config.
     *
     * @param array $roles The roles config array.
     */
    public static function save_wholesale_roles( array $roles ) {
        return update_option( 'yaywholesaleb2b_roles', $roles );
    }

    /**
     * Get default wholesale role config.
     *
     * @return array|null
     */
    public static function get_default_wholesale_role() {
        $wholesale_roles   = self::get_active_wholesale_roles();
        $setting           = SettingsHelper::get_settings();
        $default_role_slug = $setting['general']['default_role'];

        if ( ! empty( $default_role_slug ) ) {
            $default_role = self::get_role_by_slug( $wholesale_roles, $default_role_slug );
            if ( $default_role !== null ) {
                return $default_role;
            }
        }

        if ( ! empty( $wholesale_roles ) ) {
            return $wholesale_roles[0];
        }

        return null;
    }

    /**
     * Generate default wholesale role config.
     *
     * @return array|null
     */
    public static function generate_default_role() {
        $default_slug      = 'ywhs_default_role';
        $default_role_name = __( 'YayWholesale Role', 'yay-wholesale-b2b' );
        $default_role      = [
            'id'               => 1,
            'name'             => $default_role_name,
            'description'      => __( 'This is a default role generated by YayWholesale.', 'yay-wholesale-b2b' ),
            'discount'         => 0,
            'minOrderQuantity' => 0,
            'minOrderAmount'   => 0,
            'applyToSalePrice' => false,
            'status'           => true,
            'slug'             => $default_slug,
        ];

        add_role( $default_slug, $default_role_name, [ 'read' => true ] );
        self::save_wholesale_roles( [ $default_role ] );
        return $default_slug;
    }

    /**
     * Generate a unique role slug.
     *
     * @param string  $name The role name.
     * @param array[] $roles The roles array.
     * @return string The unique role slug.
     */
    public static function generate_unique_role_slug( string $name, array $roles ): string {
        $base  = sanitize_title( $name );
        $slugs = array_column( $roles, 'slug' );
        $slug  = $base;
        $i     = 1;
        while ( in_array( $slug, $slugs, true ) ) {
            $slug = "{$base}-{$i}";
            ++$i;
        }
        return $slug;
    }


    /**
     * Remove a WordPress role by slug.
     *
     * @param string $slug The role slug.
     * @return void
     */
    public static function remove_wp_role_by_slug( string $slug ): void {
        $wp_roles = wp_roles();
        if ( $wp_roles->is_role( $slug ) ) {
            $wp_roles->remove_role( $slug );
        }
    }

    /**
     * Get role config by slug.
     *
     * @param array[] $roles The roles array.
     * @param string  $slug The role slug.
     * @return array|null The role config or null if not found.
     */
    public static function get_role_by_slug( array $roles, string $slug ) {
        return array_values( array_filter( $roles, fn( $role ) => isset( $role['slug'] ) && $role['slug'] === $slug ) )[0] ?? null;
    }

    /**
     * Delete all the yay-wholesale-b2b's roles from the user.
     *
     * @param \WP_User $user The user object.
     * @return void
     */
    public static function remove_ywhs_role_from_user( \WP_User $user ): void {
        $all_role_configs = self::get_wholesale_roles();
        $role_slugs       = array_column( $all_role_configs, 'slug' );

        foreach ( $role_slugs as $ywhs_role ) {
            if ( in_array( $ywhs_role, $user->roles, true ) ) {
                $user->remove_role( $ywhs_role );
            }
        }
    }

    /**
     * Handle the data of roles list option with setting
     *
     * @param array $roles The roles option.
     * @param array $settings The settings.
     * @return array
     */
    public static function handle_roles_data( array $roles, array $settings ) {
        foreach ( $roles as $key => &$role ) {
            $slug          = $role['slug'] ?? sanitize_title( $role['name'] );
            $user_query    = new WP_User_Query(
                [
                    'role'   => $slug,
                    'fields' => 'ID',
                    'number' => -1,
                ]
            );
            $count         = $user_query->get_total();
            $role['count'] = $count;
            if ( $count > 0 ) {
                $role['role_url'] = admin_url( 'users.php?role=' . rawurlencode( $slug ) );
            }
            $role['isDefault'] = $slug === $settings['general']['default_role'];

            if ( $role['isDefault'] ) {
                $default_index = $key;
            }

            $role['minOrderQuantity'] = RequirementHelper::get_min_order_quantity( $role );
        }//end foreach

        if ( isset( $default_index ) && $default_index < count( $roles ) - 1 ) {
            $default_role = $roles[ $default_index ];
            unset( $roles[ $default_index ] );
            $roles   = array_values( $roles );
            $roles[] = $default_role;
        }

        return $roles;
    }

    public static function count_users_by_role( string $role_slug ) {
        $user_query = new WP_User_Query(
            [
                'role'   => $role_slug,
                'fields' => 'ID',
                'number' => -1,
            ]
        );
        return $user_query->get_total();
    }
}
