<?php
/**
 * Plugin adapter for Yay Wholesale B2B Lite.
 * Generated by yaycommerce-init. Edit values as needed.
 *
 * @package yaycommerce/yay-wholesale
 */

namespace YayWholesaleB2B;

defined( 'ABSPATH' ) || exit;

/**
 * YayWholesaleB2B Adapter (Lite)
 */
class YayWholesaleB2BLicenseAdapter implements \YayWholesaleB2BScoped\YayCommerce\AdminShell\Contracts\PluginMenuAdapter {
    // --- Menu methods ---
    public function get_menu_title(): string {
        return 'Yay Wholesale B2B'; }
    public function get_page_title(): string {
        return 'Yay Wholesale B2B'; }
    public function get_menu_slug(): string {
        return 'yay_wholesale_b2b'; }
    public function get_settings_page_callback(): ?callable {
        return function () {
            echo '<div id="yay-wholesale-b2b"></div>';
        };
    } // Set your render callback here
    public function get_settings_page_position(): ?int {
        return YAYWHOLESALEB2B_MENU_ORDER; }
    public function get_capability(): string {
        return 'manage_woocommerce'; }
    public function get_plugin_basename(): string {
        return YAYWHOLESALEB2B_BASE_NAME; }
    public function get_settings_label(): string {
        return 'Settings'; }
    public function get_docs_url(): string {
        return 'https://docs.yaycommerce.com/yaywholesale/'; }
    public function get_pro_url(): string {
        return 'https://yaycommerce.com/yay-wholesale-b2b-for-woocommerce/'; }
}
